### ISSUE TITLE
Fix large dataset param performance

### ISSUE THREAD

**Issue by ryanrdoherty** [VEuPathDB/ApiCommonModel#13]
(this issue was triggered by the connection timeout in VB on July 25-26 , seems the cause was a user running  geneId slow searches, each trying to create a new cache table  and some got stuck in oracle)

This issue has been co-opted from the description below to instead rework how dataset param data is imported into a WDK cache table.  Reading data over the DB link as a subquery has been shown to be consistently slow and exponentially slower as data size grows.  Thus, maybe we can get a speed-up if we create a temp table in appDb containing the dataset_values rows for a particular dataset and use, as the dataset param's internal value, a select * from the_tmp_table.  This would not be hard to set up (would just need to build the table when asked for the dataset param's internal value), but we will have to add a mechanism to tear the table down when complete.  Steve suggested reusing tables (one per dataset_id) but this would require additional concurrency logic akin to the WDK cache.  Or we could just let them sit out there and add their deletion to the wdkCache clearing logic.

First  step, however is to confirm that ID query's ID sql is significantly faster when reading from a tmp table in appDb than it is when reading from dataset_values over the db link AND make sure that create table as (select from dataset_values) is not so slow that it offsets any performance gains.  In short, check to make sure creating a tmp table from select over db_link + reading from tmp table is significantly faster than selecting directly over db_link.

**Comment by aurreco-uga** [comment]
i did some testng in my vectorbase (durian): (had to comment out in [ListDatasetParser.java](https://github.com/VEuPathDB/WDK/commit/105c37d3e1a14910880684623de65b8580d353a4#diff-1a6f56b10269e84dff59ca03d5d0e86dcc1e1dabfe10f0a5737415ae3608cbe5) lines 78-81 to allow an rtf file)
1- the times using regex and replace, or only replace or nothing,  using an rtf original file with 1200 genes:  
20mn with rgex and replace, 4mn with only replace and 17 sec with nothing. 
i should probably try with a larger txt file..
2- about dataset values stored with a space in the middle of the value (we saw we dont have cases with trailing or leading spaces), example: 
     SQL> select data1 from userlogins5.dataset_values where dataset_id = 220700633;
    AAEL000551, AAEL007948, AAEL008489
 i tested an input with 3 iDs separated by comma and space and it works well so no idea how that happened..

**Comment by aurreco-uga** [comment]
sep 8, 2022: i committed in prod and master
https://github.com/VEuPathDB/ApiCommonModel/commit/207c21b9731b47d4bf4a963768f2f6a7bc881dcf

reason to remove space: no cases in database of a space coming with an ID (leading , trailing or in the middle).

reasons to remove wildcard:
1---wildcard is very slow, and breaks the system
1.a) the times using regex and replace, or only replace or nothing, using an rtf original file with 1200 genes:
       20mn with regex_replace space and replace wildcard, 4mn with only replace wildcard and 17 sec with nothing.
1.b) can u repeat the GenesById experiment,  this time with valid but large input?

2---is hardly used anymore, now that we have ss
about wildcard use it does seem it has decreased
  2018:    27312
  2019:     1336
  2020:     5122
  2021:      598
  2022:      177
